### ISSUE TITLE
Why do me and Julius have different offline heat flux calculations?

### ISSUE THREAD

**Issue by panalluri** [ocean-transport/air-sea-ML#4]
There is clearly a difference, so I will try to plot some maps of how my calculations differ from Julius's, and track the issue on this thread. The comparison plot is below

<img width="635" alt="Screenshot 2024-06-24 at 10 43 43 AM" src="https://github.com/ocean-transport/air-sea-ML/assets/87414210/c0114400-f820-4178-9fec-8e13f58b3807">

**Comment by panalluri** [comment]
This is Julius's offline heat flux calculations 

ds = xr.open_dataset("gs://leap-persistent/jbusecke/scale-aware-air-sea/v1.0.1/fluxes/CESM_fluxes_filter_prod.zarr", engine='zarr')
ds

**Comment by panalluri** [comment]
My offline flux dataset gets its time stamps from the function preprocess_data() within preprocessing.py

**Comment by jbusecke** [comment]
The snippet pasted above loads the CESM data!

This should work:
```python
import xarray as xr
ds = xr.open_dataset("gs://leap-persistent/jbusecke/scale-aware-air-sea/v1.0.1/fluxes/CM26_fluxes_filter_prod.zarr", engine='zarr')
ds
```

> [!TIP] 
> 
> Make sure to always include relevant imports (here `xarray`) so the snippet is truly copy pasteable
> Just style, but if you wrap your code in 
> ````
> ```python
> your code
> ```
> `````
> You get nice syntax highlighting and copy button for free

**Comment by jbusecke** [comment]
Also: Sorry about posting the wrong snippet in the first place! That was on me.

**Comment by panalluri** [comment]
Could we have different fluxes because Julius has included the ice mask and I have not?
<img width="487" alt="Screenshot 2024-06-24 at 4 01 39 PM" src="https://github.com/ocean-transport/air-sea-ML/assets/87414210/65001357-1c72-41fd-8788-c3b43f27469d">

**Comment by panalluri** [comment]
I didn't include an ice mask! Now that I have I match Julius exactly!
<img width="645" alt="Screenshot 2024-06-25 at 10 16 23 AM" src="https://github.com/ocean-transport/air-sea-ML/assets/87414210/f4321955-6c04-4d1c-873d-3d7eda6206c6">
