### ISSUE TITLE
Weighted average for online momentum/freshwater fluxes

### ISSUE THREAD

**Issue by panalluri** [ocean-transport/air-sea-ML#7]
The online flux data from CM2.6 does not have grid cell area included in the dataset. It looks like we must compute this ourself in order to do a proper weighted average. How can I compute the grid cell areas? The coordinates of the dataset are below. Note that grid cell area is not a data variable either!
Do we take into comparison the curvature of the earth?

<img width="867" alt="Screenshot 2024-06-25 at 10 28 54 AM" src="https://github.com/ocean-transport/air-sea-ML/assets/87414210/a632144a-d3dc-41b0-b1cf-aef309cee49e">

**Comment by panalluri** [comment]
The code to load the dataset is below!

#online fluxes

import gcsfs
import xarray as xr
path = "gs://cmip6/GFDL_CM2_6/control/ocean_boundary"
ds = xr.open_dataset(path, engine='zarr', chunks={})
ds

**Comment by panalluri** [comment]
Could the grid cell areas be the same as our offline flux dataset? I will test the xt_ocean and yt_ocean coordinates. The freshwater flux is on the t-cell grid, so that works well. However, the momentum flux is on the u-cell grid. Are u-cell and t-cell grids guaranteed to have the same grid cell areas? How should I calculate u-cell grid cell areas? Do I take into account the curvature of the earth? Or can I just assume I have a rectangle bounded by the given latitude and longitude bounds?

**Comment by panalluri** [comment]
I am curious about trying the following command

from intake import open_catalog

cat = open_catalog("https://raw.githubusercontent.com/pangeo-data/pangeo-datastore/master/intake-catalogs/ocean/GFDL_CM2.6.yaml")
ds  = cat["GFDL_CM2_6_grid"].to_dask()

This comes from the GFDL CM2.6 Pangeo catalog: https://catalog.pangeo.io/browse/master/ocean/GFDL_CM2_6/GFDL_CM2_6_grid/

It does include an area_u and area_t
<img width="742" alt="Screenshot 2024-06-25 at 10 51 52 AM" src="https://github.com/ocean-transport/air-sea-ML/assets/87414210/5af37729-d415-4453-9ac1-1013dba7fe40">

**Comment by panalluri** [comment]
Yes, the latitudes and longitudes for the t-cell and u-cell grids match! The areas from the Pangeo CM2.6 grid details data set were used to find freshwater and momentum fluxes!

**Comment by jbusecke** [comment]
Nice seems like you got this figured out. For clarification: CM2.6 uses an [Arakawa B Grid](https://en.wikipedia.org/wiki/Arakawa_grids), where both velocity components are located on the cell corner.
